# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160710_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='hh', max_length=100),
            preserve_default=False,
        ),
    ]
