# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160717_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='content',
            new_name='contents',
        ),
    ]
